

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mySQL
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:



#  springboot-app:
#    image: your-springboot-image:latest     # <-- replace this with the image name you built
#    container_name: springboot-app
#    depends_on:
#      - mysql
#      - mongo
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/testdb?authSource=admin
#    ports:
#      - "8080:8080"

#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mySQL
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password

#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - "27017:27017"
